create table if not exists projects (
  id integer primary key generated by default as identity,
  name text not null check (name <> ''),
  priority integer not null,
  description text,
  deliverydate date not null
);

create table if not exists tasks (
  id integer primary key generated by default as identity,
  name text not null check (name <> ''),
  priority integer not null,
  done boolean,
  projectid integer references projects(id)
);

INSERT INTO projects (name, priority, description, deliverydate) VALUES ('MAKE A WEB APP', 1, 'USANDO JAVASCRIPT', '2020-05-12');
INSERT INTO projects (name, priority, description, deliverydate) VALUES ('MAKE A WEB APP 1', 2, 'USANDO JAVASCRIPT', '2005-05-12');
INSERT INTO projects (name, priority, description, deliverydate) VALUES ('MAKE A WEB APP 2', 3, 'USANDO JAVASCRIPT', '2017-05-12');
INSERT INTO projects (name, priority, description, deliverydate) VALUES ('MAKE A WEB APP 3', 2, 'USANDO JAVASCRIPT', '2018-05-12');
INSERT INTO projects (name, priority, description, deliverydate) VALUES ('MAKE A WEB APP 4', 2, 'USANDO JAVASCRIPT', '2016-05-12');
INSERT INTO projects (name, priority, description, deliverydate) VALUES ('MAKE A WEB APP 5', 4, 'USANDO JAVASCRIPT', '2019-05-12');

INSERT INTO tasks (name, priority, done, projectid) VALUES ('tarea 1', 2, false, 1);
INSERT INTO tasks (name, priority, done, projectid) VALUES ('tarea 2', 2, true, 4);
INSERT INTO tasks (name, priority, done, projectid) VALUES ('tarea 3', 3, true, 3);
INSERT INTO tasks (name, priority, done, projectid) VALUES ('tarea 4', 1, false, 2);

